name: 构建KBE项目
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: 构建项目
      run: |
        deb http://mirrors.aliyun.com/ubuntu/ bionic main restricted universe multiverse
        deb http://mirrors.aliyun.com/ubuntu/ bionic-security main restricted universe multiverse
        deb http://mirrors.aliyun.com/ubuntu/ bionic-updates main restricted universe multiverse
        deb http://mirrors.aliyun.com/ubuntu/ bionic-proposed main restricted universe multiverse
        deb http://mirrors.aliyun.com/ubuntu/ bionic-backports main restricted universe multiverse
        deb-src http://mirrors.aliyun.com/ubuntu/ bionic main restricted universe multiverse
        deb-src http://mirrors.aliyun.com/ubuntu/ bionic-security main restricted universe multiverse
        deb-src http://mirrors.aliyun.com/ubuntu/ bionic-updates main restricted universe multiverse
        deb-src http://mirrors.aliyun.com/ubuntu/ bionic-proposed main restricted universe multiverse
        deb-src http://mirrors.aliyun.com/ubuntu/ bionic-backports main restricted universe multiverse
        gpg --keyserver keyserver.ubuntu.com --recv 3B4FE6ACC0B21F32
        gpg --export --armor 3B4FE6ACC0B21F32 | apt-key add -
        sudo apt update
        sudo apt upgrade
        sudo apt install -y libssl-dev mysql-server-5.7 libmysqlclient-dev
        cd kbe/src/
        chmod -R 755 .
        make CXXFLAGS += -O3
        cd ../bin
        ls
    - name: 上传APK
      uses: actions/upload-artifact@v4
      with:
        name: kbengine
        path: kbe/bin/server/*/**
