name: 构建KBE项目
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: msbuild kbe\src\kbengine_vs**.sln /t:Rebuild /p:Configuration=Release
    - name: 上传APK
      uses: actions/upload-artifact@v4
      with:
        name: kbe
        path: kbe/bin/server/*/**
