name: 构建KBE项目
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: 构建项目
      run: |
        sudo apt update
        sudo apt upgrade
        sudo apt install -y libssl-dev mysql-server libmysqlclient-dev
        ls
        cd kbe/src/
        chmod -R 755 .
        make
        cd ../bin
        ls
    - name: 上传APK
      uses: actions/upload-artifact@v4
      with:
        name: kbengine
        path: kbe/bin/server/*/**
