name: 构建KBE项目
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: 构建项目
      run: |
        deb http://repo.mysql.com/apt/ubuntu/ bionic mysql-apt-config
        deb http://repo.mysql.com/apt/ubuntu/ bionic mysql-5.7
        deb http://repo.mysql.com/apt/ubuntu/ bionic mysql-tools
        deb-src http://repo.mysql.com/apt/ubuntu/ bionic mysql-5.7
        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 76F1A20FF987672F
        sudo apt update
        sudo apt upgrade
        sudo apt install -y libssl-dev mysql-server-5.7 libmysqlclient-dev
        cd kbe/src/
        chmod -R 755 .
        make CXXFLAGS += -O3
        cd ../bin
        ls
    - name: 上传APK
      uses: actions/upload-artifact@v4
      with:
        name: kbengine
        path: kbe/bin/server/*/**
