name: 构建KBE项目
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: 安装依赖
      run: |
        sudo apt update
        sudo apt upgrade
        sudo apt install -y libssl-dev mysql-server libmysqld-dev
    - name: make
      run: |
        cd keb/src/ && chmod -R 755 . && make
        cd ../bin/
        ls
    - name: 上传APK
      uses: actions/upload-artifact@v4
      with:
        name: kbe
        path: kbe/bin/server/*/**
